// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsO9CE_8Yg57F4mlU7OJu3nwRcW8XKmYs',
    appId: '1:542371924030:web:c01df3b573a83afbf6e96f',
    messagingSenderId: '542371924030',
    projectId: 'budgetbunny-e2613',
    authDomain: 'budgetbunny-e2613.firebaseapp.com',
    storageBucket: 'budgetbunny-e2613.firebasestorage.app',
    measurementId: 'G-6EBCG5SGJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDic37MpnP3H8dyC9TxwLNUEcNZROYQ2LA',
    appId: '1:542371924030:android:311aa3582fb894aaf6e96f',
    messagingSenderId: '542371924030',
    projectId: 'budgetbunny-e2613',
    storageBucket: 'budgetbunny-e2613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrJO_dEQcwI-9ICEfLbxa90TNhNVZ6Chs',
    appId: '1:542371924030:ios:da083e17f2772394f6e96f',
    messagingSenderId: '542371924030',
    projectId: 'budgetbunny-e2613',
    storageBucket: 'budgetbunny-e2613.firebasestorage.app',
    iosBundleId: 'com.example.budgetbunny',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrJO_dEQcwI-9ICEfLbxa90TNhNVZ6Chs',
    appId: '1:542371924030:ios:37d2859da7f06521f6e96f',
    messagingSenderId: '542371924030',
    projectId: 'budgetbunny-e2613',
    storageBucket: 'budgetbunny-e2613.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsO9CE_8Yg57F4mlU7OJu3nwRcW8XKmYs',
    appId: '1:542371924030:web:f891ad72f9447172f6e96f',
    messagingSenderId: '542371924030',
    projectId: 'budgetbunny-e2613',
    authDomain: 'budgetbunny-e2613.firebaseapp.com',
    storageBucket: 'budgetbunny-e2613.firebasestorage.app',
    measurementId: 'G-WGZBRLG30X',
  );
}
